#!/bin/bash

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm *log*
rm alpha.water
rm deposit_area
rm blockMeshDict
#------------------------------------------------------------------------------
