#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh
runApplication setFields
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar
runApplication topoSet
setsToZones
runApplication postProcess -func calculationAreaIntegrateAlphaWater
mv log.postProcess log.postProcess0
runApplication postProcess -func finishAreaIntegrateAlphaWater

#------------------------------------------------------------------------------
