#!/bin/bash
set -x

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rho_ind="2"
rho_pattern="    rho             rho [ 1 -3 0 0 0 0 0 ] "
rho[1]="250"
rho[2]="200"
rho[3]="150"

nu0_ind="5"
nu0_pattern="		nu0             nu0   [ 0 2 -1 0 0 0 0 ] "
nu0[1]="1e5"
nu0[2]="1e6"
nu0[3]="1e7"
nu0[4]="1e8"
nu0[5]="1e9"

tau0_ind="1 2 3 4 5"
tau0_pattern="		tau0            tau0  [ 0 2 -2 0 0 0 0 ] "
tau0[1]="15"
tau0[2]="18"
tau0[3]="22"
tau0[4]="25"
tau0[5]="30"
#tau0[1]="1"
#tau0[2]="5"
#tau0[3]="10"
#tau0[4]="20"
#tau0[5]="50"

k_ind="1 2 3 4 5 6 7"
k_pattern="		k               k     [ 0 2 -1 0 0 0 0 ] "
k[1]="2"
k[2]="3"
k[3]="4"
k[4]="6"
k[5]="7"
k[6]="8"
k[7]="9"
#k[1]="1e-4"
#k[2]="1e-3"
#k[3]="1e-2"
#k[4]="1e-1"
#k[5]="1"
#k[6]="5"
#k[7]="10"

n_ind="1"
n_pattern="		n               n     [ 0 0  0 0 0 0 0 ] "
n[1]="0.8"
n[2]="0.5"
n[3]="0.6"
n[4]="1"

#mkdir pics

for arg1 in $rho_ind
do
	for arg2 in $nu0_ind
	do
		for arg3 in $tau0_ind
		do
			for arg4 in $k_ind
			do
				for arg5 in $n_ind
				do
					cp -r blockMesh_setFields_orig rho${rho[$arg1]}_nu0${nu0[$arg2]}_tau0${tau0[$arg3]}_k${k[$arg4]}_n${n[$arg5]}
					cd rho${rho[$arg1]}_nu0${nu0[$arg2]}_tau0${tau0[$arg3]}_k${k[$arg4]}_n${n[$arg5]}/
					sed "s/rho_pattern/$rho_pattern${rho[$arg1]};/" constant/transportProperties > tmp
					mv tmp constant/transportProperties
					sed "s/nu0_pattern/$nu0_pattern${nu0[$arg2]};/" constant/transportProperties > tmp
					mv tmp constant/transportProperties
					sed "s/tau0_pattern/$tau0_pattern${tau0[$arg3]};/" constant/transportProperties > tmp
					mv tmp constant/transportProperties
					sed "s/k_pattern/$k_pattern${k[$arg4]};/" constant/transportProperties > tmp
					mv tmp constant/transportProperties
					sed "s/n_pattern/$n_pattern${n[$arg5]};/" constant/transportProperties > tmp
					mv tmp constant/transportProperties
					./Allrun
					mkdir pics
					cp ../depositZone.py ./
					touch foam.foam
					~/Software/ParaView-5.9.0-MPI-Linux-Python3.8-64bit/bin/pvpython --force-offscreen-rendering depositZone.py
					cd ../
				done
			done
		done
	done
done

mkdir pics

for arg1 in $rho_ind
do
	for arg2 in $nu0_ind
	do
		for arg5 in $n_ind
		do
			for arg3 in $tau0_ind
			do
			cp rho${rho[$arg1]}_nu0${nu0[$arg2]}_tau0${tau0[$arg3]}_k${k[1]}_n${n[$arg5]}/pics/depositZone.png pics/set2tmp${tau0[$arg3]}
				for arg4 in $k_ind
				do
					if test $arg4 -gt 1
					then
						convert -append pics/set2tmp${tau0[$arg3]} rho${rho[$arg1]}_nu0${nu0[$arg2]}_tau0${tau0[$arg3]}_k${k[$arg4]}_n${n[$arg5]}/pics/depositZone.png pics/set2tmp${tau0[$arg3]}
					fi
				done
				convert pics/set2tmp${tau0[$arg3]} -resize 50% pics/set2tmp${tau0[$arg3]}
				if test $arg3 -gt 1
				then
					convert +append pics/set2 pics/tau0${tau0[$arg3]} pics/set2
				else
					cp pics/set2tmp${tau0[1]} pics/set2
				fi
			done
		done
	done
done
