#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# copy flange surface from resources directory
#cp $FOAM_TUTORIALS/resources/geometry/flange.stl.gz constant/triSurface/

runApplication blockMesh
#runApplication surfaceFeatures
#runApplication snappyHexMesh -overwrite
runApplication setFields
runApplication decomposePar
#runApplication interFoam
runParallel interFoam
runApplication reconstructPar
runApplication topoSet
setsToZones
runApplication postProcess -func calculationAreaIntegrateAlphaWater
mv log.postProcess log.postProcess0
runApplication postProcess -func finishAreaIntegrateAlphaWater
