#!/bin/sh
#source ~/OpenFOAM/OpenFOAM-v1912/etc/bashrc
#cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

#runApplication blockMesh
#runApplication setFields
#runApplication $(getApplication)
#runApplication decomposePar -constant
#runParallel $(getApplication)
runParallel postProcess -parallel -func devRhoReff
#runApplication postProcess -func wallShearStress
#runApplication reconstructPar
#runApplication postProcess -func outputSurfaceIntegrateAlphaWater
#python3 calcOutputFlowHeight.py

#------------------------------------------------------------------------------
